### ISSUE TITLE
Update image locations to github repo

### ISSUE THREAD

**Issue by jeremyallenjacobson** [ka4on/QTM350-Final-Project#1]
Nice project! I wanted to share this with my colleagues. I think it would be a valuable resource on Textract. Can you update the image locations to the repo so that the image links in the notebooks work? That would be awesome!

**Comment by ka4on** [comment]
Thanks professor! I will try to update the images if I can. I'm also not quite sure why some of the images work but others don't, will try my best to fix those!

**Comment by jeremyallenjacobson** [comment]
That will be great.

It is just that the AWS credits run out after a fixed period of time. As long as the pictures aren't to numerous, they should fit in the github repo.

Best wishes,
Jeremy
________________________________
From: Kairan Zhong ***@***.***>
Sent: Tuesday, April 11, 2023 1:28 PM
To: ka4on/QTM350-Final-Project ***@***.***>
Cc: Jacobson, Jeremy ***@***.***>; Author ***@***.***>
Subject: [External] Re: [ka4on/QTM350-Final-Project] Update image locations to github repo (Issue #1)


Thanks professor! I will try to update the images if I can. I'm also not quite sure why some of the images work but others don't, will try my best to fix those!

**Comment by ka4on** [comment]
Hi professor, I just fixed the images in the notebook, and everything should work fine now. Please take a look and let me know if there is any problem. Thanks!

**Comment by jeremyallenjacobson** [comment]
Awesome, that was quick, looks great! I will share this with my colleagues.
Best wishes,
Jeremy
________________________________
From: Kairan Zhong ***@***.***>
Sent: Tuesday, April 11, 2023 2:26 PM
To: ka4on/QTM350-Final-Project ***@***.***>
Cc: Jacobson, Jeremy ***@***.***>; Author ***@***.***>
Subject: [External] Re: [ka4on/QTM350-Final-Project] Update image locations to github repo (Issue #1)


Hi professor, I just fixed the images in the notebook, and everything should work fine now. Please take a look and let me know if there is any problem. Thanks!
